version: "3.9"

services:
  backend:
    build: ./backend
    container_name: Ai_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434/api/chat
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  frontend:
    build: ./frontend
    container_name: Ai_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: always
